version: "3"
services:
  nginx:
    container_name: nginx
    hostname: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./wwwroot:/var/www/html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
    ports:
      - 8980:80
    environment:
      PS1: "\\u@\\h:\\w\\$$ "
    depends_on:
      - "php-fpm"
    restart: always
  

  php-fpm:
    container_name: php-fpm
    hostname: php-fpm
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./log/php-fpm/:/var/log/php-fpm
      - ./wwwroot:/var/www/html:ro
    environment:
      PS1: "\\u@\\h:\\w\\$$ "
    restart: always


  mysql:
    container_name: mysql
    hostname: mysql    
    build:
      context: ./mysql
    env_file:
        - ".env"
    environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
        - "8906:3306"
    volumes:
        - "./data/db/mysql:/var/lib/mysql"
    restart: always